languageCode = "en"
languageName = "English"
weight = 1
title = "River Romney"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Welcome to my portfolio."

[params.author]
  name = "River"
  email = "contact@riverromney.com"
  image = "img/blowfish_logo.png"
  headline = "Welcome to my portfolio."
  bio = "Welcome to my portfolio."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]